# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(430, 60, 731, 711))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_show_camera = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_show_camera.setFont(font)
        self.label_show_camera.setScaledContents(False)
        self.label_show_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_camera.setObjectName("label_show_camera")
        self.gridLayout.addWidget(self.label_show_camera, 0, 0, 1, 1)
        self.label_show_camera1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_show_camera1.setFont(font)
        self.label_show_camera1.setScaledContents(False)
        self.label_show_camera1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_camera1.setObjectName("label_show_camera1")
        self.gridLayout.addWidget(self.label_show_camera1, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.button_hole_filling = QtWidgets.QPushButton(self.centralwidget)
        self.button_hole_filling.setGeometry(QtCore.QRect(150, 240, 171, 61))
        self.button_hole_filling.setObjectName("button_hole_filling")
        self.button_open_camera = QtWidgets.QPushButton(self.centralwidget)
        self.button_open_camera.setGeometry(QtCore.QRect(150, 140, 171, 61))
        self.button_open_camera.setObjectName("button_open_camera")
        self.button_open_camera_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_open_camera_2.setGeometry(QtCore.QRect(150, 340, 171, 61))
        self.button_open_camera_2.setObjectName("button_open_camera_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_show_camera.setText(_translate("MainWindow", "Camera_1 RGB"))
        self.label_show_camera1.setText(_translate("MainWindow", "Camera_1 Depth"))
        self.label_4.setText(_translate("MainWindow", "Camera_2 Depth"))
        self.label_2.setText(_translate("MainWindow", "Camera_2 RGB"))
        self.button_hole_filling.setText(_translate("MainWindow", "孔洞填充"))
        self.button_open_camera.setText(_translate("MainWindow", "打开相机"))
        self.button_open_camera_2.setText(_translate("MainWindow", "关闭相机"))
